# 项目相关配置
itclub:
  # 名称
  name: ItClub
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2023
  # 本地文件路径 示例（ Windows配置D:/itclub/uploadPath，Linux配置 /home/itclub/uploadPath）
  profile: D:/itclub/uploadPath


server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
      # 文件上传

spring:
  profiles:
    # 添加多个配置文件用,隔开 如：dev,oss
    active: sharding,activiti
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB


# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.itclub.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  # 关闭logo打印
  global-config:
    banner: false


# 日志配置
logging:
  level:
    com.itclub: debug
    org.springframework: warn

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*